import React from "react";
import { SimpleSlider } from "../src/containers";
import { Layout } from "../src/template/Layout";
import Head from "next/head";

const Home = () => {
  return (
    <div>
      <Head>
          <title>Tiki</title>
          <meta name="description" content="Generated by create next app" />
          
      </Head>

      <Layout>
        <div className="">
          <SimpleSlider/>
        </div>
      </Layout>
    </div>
  );
};

export default Home;
